workspaceDependencies {
	siblingMaven('HudRendererLib') {
		coordinate.set("io.github.brainage04:hudrendererlib:${rootProject.hudrendererlib_version}")
		siblingDirectory.set(rootProject.layout.projectDirectory.dir('../HudRendererLib'))
	}
}

dependencies {
	implementation "io.github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
	productionRuntimeMods "io.github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
}
