modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="fortniteinminecraft"
version="${version}"
displayName="Fortnite In Minecraft"
authors="brainage04"
description='''Server and client Fortnite building and combat mechanics prototype.'''

[[mixins]]
config="fortniteinminecraft.mixins.json"

[[mixins]]
config="fortniteinminecraft.client.mixins.json"

[[dependencies.fortniteinminecraft]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.fortniteinminecraft]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.fortniteinminecraft]]
modId="hudrendererlib"
type="required"
versionRange="[${hudrendererlib_version},)"
ordering="NONE"
side="CLIENT"
