workspaceDependencies {
	siblingMaven('HudRendererLib') {
		coordinate.set("io.github.brainage04:hudrendererlib-neoforge:${rootProject.hudrendererlib_version}")
		siblingDirectory.set(rootProject.layout.projectDirectory.dir('../HudRendererLib'))
	}
}

modPublishing.github.enabled.set(false)
modPublishing.modrinth.enabled.set(false)
modPublishing.curseforge.enabled.set(false)

dependencies { implementation "io.github.brainage04:hudrendererlib-neoforge:${rootProject.hudrendererlib_version}" }
